/** Columnas del SELECT de sp_rpt_polizas expuestas en grilla */
export const POLIZAS_COLUMN_ORDER = [
  'numero_poliza',
  'numero_poliza_relacionada',
  'fecha_emision_poliza',
  'fecha_desde_poliza',
  'fecha_hasta_poliza',
  'estado',
  'ramo',
  'tipo_ramo',
  'plan',
  'forma',
  'frecuencia',
  'sucursal',
  'canal_venta',
  'canal_alterno',
  'productor',
  'estatus_poliza',
  'moneda',
  'prima_total',
  'tomador',
  'asegurado',
  'beneficiario',
  'marca_vehiculo',
  'modelo_vehiculo',
  'version_vehiculo',
  'anio_vehiculo',
  'placa',
  'color_vehiculo',
  'serial_carroceria',
  'serial_motor',
] as const;

/** Columnas del SELECT de sp_rpt_comisiones expuestas en grilla */
export const COMISIONES_COLUMN_ORDER = [
  'numero_poliza',
  'numero_recibo',
  'ramo',
  'tomador',
  'asegurado',
  'fecha_emision_recibo',
  'fecha_desde_recibo',
  'fecha_hasta_recibo',
  'dias_vigencia',
  'estado_recibo',
  'estado_recibo_desc',
  'fecha_cobro_recibo',
  'numero_ingreso',
  'moneda_recibo',
  'suma_asegurada',
  'suma_asegurada_ext',
  'monto_recibo_bruto',
  'monto_recibo_bruto_ext',
  'monto_recibo_pagado',
  'monto_recibo_pagado_ext',
  'sucursal',
  'productor',
  'tipo_persona_productor',
  'tipo_movimiento_codigo',
  'tipo_movimiento',
  'monto_movimiento',
  'monto_movimiento_bs',
  'monto_movimiento_ext',
  'porcentaje_comision',
  'porcentaje_islr',
  'monto_islr',
  'moneda_cobro',
  'moneda_pago',
  'tasa_cobro',
  'numero_orden_pago',
  'banco',
  'referencia_bancaria',
  'fecha_pago_comision',
  'monto_sustraendo',
  'monto_neto_orden',
  'monto_islr_orden',
  'monto_bruto_orden',
] as const;

export const DEFAULT_GRID_COLUMNS_BY_SLUG: Record<string, readonly string[]> = {
  RPT_POLIZAS: POLIZAS_COLUMN_ORDER,
  RPT_COMISIONES: COMISIONES_COLUMN_ORDER,
};
